Repository DEFRA/water-abstraction-tactical-crm, pull requests merged in 2022-10, with the labels that each got.

#919 Fix problem licence data
  migrations/20221018092848-remove-problem-licences.js
  migrations/sqls/20221018092848-remove-problem-licences-down.sql
  migrations/sqls/20221018092848-remove-problem-licences-up.sql
Labels: bug

#920 Make auto-changelog external
  package-lock.json
  package.json
Labels: housekeeping

#921 Revert changelog script change with improvements
  package.json
Labels: housekeeping

#923 Create `/health/info` endpoint
  src/modules/health/controller.js
  src/modules/health/routes.js
  src/routes/crm.js
  test/modules/health/controller.test.js
Labels: enhancement
